/*
 * Get Playoff Skater Stats Constants
 */
export const STATS_PLAYOFF_SKATER_GET_SUCCESS = 'STATS_PLAYOFF_PLAYER_GET_SUCCESS';
export const STATS_PLAYOFF_SKATER_GET_ERROR = 'STATS_PLAYOFF_SKATER_GET_ERROR';